const dataBuku = [
  {no:1,judul:"Pembangunan dan Pengembangan Kawasan Geopark Indonesia",pengarang:"Sofyan Suwardi, Yunus Kusumahbrata, Hanang Samodra",penerbit:"Badan Geologi Kementrian ESDM",tahun:2016,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:2,judul:"Udara Perkotaan Dalam Pembangunan Kota yang Berkelanjutan",pengarang:"Ridwan D. Tamin, Heirma S. Poernomo",penerbit:"ADEKSI, KAS, GTZ ProLH",tahun:2009,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:3,judul:"Pengembangan Kawasan Strategis Ekonomi",pengarang:"Lutfi Muta'ali",penerbit:"Badan Penerbit Fakultas Geografi (BPFG) UGM Yogyakarta",tahun:2015,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:4,judul:"Pembangunan Berkelanjutan dari MDGs ke SDGs",pengarang:"Suryo Sakti Hadiwijoyo, Betty Wahyu Nilla SFDA, Arista Ayu Nanda",penerbit:"Spektrum Nusantara",tahun:2019,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:5,judul:"Kesehatan Lingkungan",pengarang:"Atrisman Nukman",penerbit:"ADEKSI, KAS, GTZ ProLH",tahun:2009,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:6,judul:"Tata Ruang Dalam Pembangunan Kota yang Berkelanjutan",pengarang:"Guritno Soerjodibroto",penerbit:"ADEKSI, KAS, GTZ ProLH",tahun:2009,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:7,judul:"Transportasi Kota Dalam Pembangunan Kota yang Berkelanjutan",pengarang:"Moekti H. Soejachmoen",penerbit:"ADEKSI, KAS, GTZ ProLH",tahun:2009,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:8,judul:"Peran DPRD Dalam Pembangunan Kota yang Berkelanjutan",pengarang:"Sarah Waddell",penerbit:"ADEKSI, KAS, GTZ ProLH",tahun:2009,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:9,judul:"Sistem Informasi Geografis Dukungan Tools dan Plug-Ins (Extentions) dalam pengembangan berbagai Aplikasi",pengarang:"Eddy Prahasta",penerbit:"Informatika",tahun:2004,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:10,judul:"Indonesia Journal of Transformation Studies",pengarang:"Wayan Dedy Juniawan, Nyoman Trisna Kurniawan, dkk",penerbit:"Perkumpulan Perencana Pembangunan Indonesia (PPPI)",tahun:2024,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:11,judul:"Jalan Panjang Mengubah Kebijakan Publik",pengarang:"Tubagus Furqon Sofhani, Arie Sujito, dkk",penerbit:"Forum Pengembangan Partisipasi Masyarakat (FPPM)",tahun:2009,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:12,judul:"Air Perkotaan Dalam Pembangunan Kota yang Berkelanjutan",pengarang:"Novalinda, Sarah Waddell",penerbit:"ADEKSI, KAS, GTZ ProLH",tahun:2009,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:13,judul:"Desentralisasi Radikal Ikhtiar Pengembangan Wilayah Imekko Sorong Selatan",pengarang:"Bambang Purwoko, Arie Ruhyanto, dkk",penerbit:"Ifada Publishing (IKAPI)",tahun:2017,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:14,judul:"Manajemen Pemerintahan Daerah Otonom Baru Praktik Baik Pemerintahan di Kab. Puncak Papua",pengarang:"Bambang Purwoko",penerbit:"Gadjah Mada University ",tahun:2018,genre:"Non Fiksi",stok:2,ket:"Tersedia"},
{no:15,judul:"COLLAPSE Runtuhnya Peradaban-peradaban Dunia",pengarang:"Jared Diamond",penerbit:"KPG (Kepustakaan Populer Gramedia)",tahun:2014,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:16,judul:"In Defense of Smokers",pengarang:"Lauren A. Colby",penerbit:"INDONESIA BERDIKARI",tahun:2014,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:17,judul:"Titik Nadir Demokrasi Kesunyian Manusia Dalam Negara",pengarang:"Emha Ainun Nadjib",penerbit:"PT Bentang Pustaka",tahun:2016,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:18,judul:"WONOSOBO Sejarah yang Terserak",pengarang:"Dwi Putranto Bimo Sasongko",penerbit:"Bimalukar Kreativa",tahun:2021,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:19,judul:"Strategi Pembangunan",pengarang:"Matathir & Soeharto",penerbit:"Pelangi Cendekia",tahun:2005,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:20,judul:"Perempuan di Wilayah Konflik",pengarang:"Gadis Arivia, Nur Iman Subono, Adriana Venny, Ida Danny, Asikin Arif",penerbit:"Yayasan Jurnal Perempuan",tahun:2002,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:21,judul:"Dilarang Berekspresi Dilarang Keluar Malam DIlarang Pilih Baju Sendiri",pengarang:"Gadis Arivia, Ratna Syafrida Dhanny, Asikin Arif",pengarang:"Yayasan Jurnal Perempuan",tahun:2008,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:22,judul:"Menelusuri Kearifan Lokal",pengarang:"Gadis Arivia, Ratna Syafrida Dhanny, Asikin Arif",penerbit:"Yayasan Jurnal Perempuan",tahun:2008,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:23,judul:"Mencari Ruang Untuk DIfabel",pengarang:"Gadis Arivia, Ratna Syafrida Dhanny, Asikin Arif",penerbit:"Yayasan Jurnal Perempuan",tahun:2010,genre:"Non Fiksi",stok:1,ket:"Tersedia"},
{no:24,judul:"Kesusastraan dan Kekuasaan",pengarang:"Goenawan Mohamad",penerbit:"PT Pustaka Firdaus",tahun:1993,genre:"Non Fiksi",stok:1,ket:"Tersedia"}
  ];
